### PR TITLE
Httpadmin

### PR DESCRIPTION
**Pull request by rkluwen**
This is an http administration interface for pluginbox.
Besides that a status can be queried, also plugins can be added and removed on the fly.
Also a per-plugin status is supported. This can be used to just return a status or to reload a configuration or otherwise.

### CODE REVIEW

**Comment by rkluwen** [comment]
To everybody who is using this. Please test this code.

**Comment by rkluwen** [comment]
Okay. So I made a nice angular interface, based on the xml info that the pluginbox now throws. And it seems that after removing and adding back some plugins, there is a crash that I am not able to put my finger on at this time. Just so you know.

**Comment by rkluwen** [comment]
Never mind. I solved it already. Please go ahead and test.

**Comment by donald-jackson** [comment]
Thanks very much for this contribution Rene, I have made some minor changes and fixes and its now committed.

**Pull request merged**
